<<<<<<< HEAD
# Generated by Django 5.x on 2026-03-19

from django.db import migrations, models


class Migration(migrations.Migration):

=======
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
>>>>>>> 08430856d59c2322acb2d319a146251f0b5a370d
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name="AnalysisResult",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("farm_name", models.CharField(max_length=255)),
                ("health_score", models.IntegerField()),
                ("actions", models.JSONField(default=dict)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("original_image_url", models.URLField(max_length=1024)),
                ("overlay_image_url", models.URLField(max_length=1024)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
=======
            name="UserProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("phone", models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name="ImageRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("original_image_url", models.URLField()),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="images", to="analyzer.userprofile"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AnalysisResult",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("health_score", models.IntegerField()),
                ("actions", models.JSONField()),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("overlay_image_url", models.URLField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "image",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="results", to="analyzer.imagerecord"),
                ),
>>>>>>> 08430856d59c2322acb2d319a146251f0b5a370d
            ],
        ),
    ]
